### ISSUE TITLE
batch_size的设置

### ISSUE THREAD

**Issue by xinyueliii** [huTao1030/DiffHDR-pytorch#1]
您好！在论文中，训练细节里写的是batch_size使用的是64，但在这个代码实现里，train_loader的batch_size使用的是8，到底应该使用哪一个呢？

**Comment by gbymat** [comment]
您好，代码中包含两种不同方案dataloader（离线/在线 数据增强）。在线数据增强的方案与论文中描述一致，即bs=8，patch_n=8，意味着会从每张图像中随机剪裁8个patch，因此实际每次迭代的mini batchs为8×8=64。

而当使用离线数据增强（gen_crop.py）时，在训练过程中我们使用8张A100基于Accelerate（[https://huggingface.co/docs/accelerate/index](url)）进行DDP并行训练。因此当单卡bs设置为8，多卡训练时实际bs为64。

由于bs相对较大，我们建议使用离线数据增强完成训练，避免数据预处理导致GPU跑不满从而影响训练速度。

**Comment by xinyueliii** [comment]
没想到能这么快就收到您的回复，我明白这个问题了，非常感谢您细致的工作和耐心的解答！
