### ISSUE TITLE
cropped_data的问题

### ISSUE THREAD

**Issue by xinyueliii** [huTao1030/DiffHDR-pytorch#2]
另外还有一个问题想要请教您：您在readme中告知可以使用预裁剪好的data进行训练，我运行了gen_crop.py文件，产生的training_data有上万张，每个epoch都需要训练很长时间，而代码里面的n_epochs是300000，我在怀疑我是不是理解错了具体实施的细节？
期待您的解惑，谢谢！

**Comment by gbymat** [comment]
你好，你的理解并没有错，实际上当crop size=128，stride=64，并且所有数据增强保持开启状态时，所产生的training_data会超过10w。我们使用8张A100使用混合精度计算完成训练大约需要十天左右。

**Comment by gbymat** [comment]
另外，正如论文里所提到的我们对模型进行n_iters=300w次迭代以完成训练，因此n_epochs=30w这一参数可以忽略。

**Comment by xinyueliii** [comment]
我明白了，感谢您如此及时的回复，细致的工作和耐心的解答！
